name: CI/CD

on:
    pull_request:
    branches:
    - main 
    - workflow
    push:
    branches: 
    - main
    - workflow
    jobs:
        build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 12
        - run: npm ci
        - run: npm test
        - run: npm run build
        - run: npm run deploy
